# Generated by Django 4.2.1 on 2023-06-18 13:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=9, null=True)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('CST', 'CST'), ('CSM', 'CSM'), ('CSD', 'CSD'), ('IT-A', 'IT-A'), ('IT-B', 'IT-B'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('ETE', 'ETE')], default=0, max_length=5)),
                ('dob', models.DateField(null=True)),
                ('phno', models.CharField(max_length=20, null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='CA.counsellor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student_opinion', models.TextField()),
                ('counsellor_remarks', models.TextField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CA.counsellor')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CA.student')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid1_marks', models.IntegerField(default=0)),
                ('mid2_marks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('consolidate_marks', models.FloatField(default=0)),
                ('external_marks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('grade_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CA.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CA.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1st'), (2, '2nd')], default=0)),
                ('sgpa', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('marks', models.ManyToManyField(to='CA.marks')),
                ('stu', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CA.student')),
                ('subjects', models.ManyToManyField(to='CA.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='CA.student')),
            ],
            options={
                'unique_together': {('s_id', 'month')},
            },
        ),
    ]
